server:
  port: 7654
  address: 0.0.0.0
  servlet-path: /contactapp


security:
  basic:
    enabled: false

database:
  url: jdbc:mysql://localhost:3306/contact_app?characterEncoding=UTF-8&useSSL=false
  user: root
  password: password
